import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/header/page";
import { MobileMenu } from "./components/mobileNav/page";
import { MenuProvider } from "./Context/MenuContext";

// Import Poppins font
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Choose appropriate weights for your design
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <MenuProvider>
        <body className={`${poppins.variable}`}>
            <Header />
            <MobileMenu />
            {children}
        </body>
      </MenuProvider>
    </html>
  );
}
